# Generated by Django 6.0.6 on 2026-06-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("language", "Programming Language"),
                            ("framework", "Framework"),
                            ("ml", "ML / Data Science"),
                            ("tool", "Tool / DevOps"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome or Devicons class",
                        max_length=100,
                    ),
                ),
                (
                    "proficiency",
                    models.PositiveIntegerField(
                        default=80, help_text="Proficiency percentage (0–100)"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["category", "order"],
            },
        ),
    ]
