# Generated by Django 6.0.6 on 2026-06-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("web", "Web Development"),
                            ("ml", "Machine Learning"),
                            ("data", "Data Analysis"),
                            ("cv", "Computer Vision"),
                        ],
                        default="web",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("short_description", models.CharField(max_length=300)),
                (
                    "tech_stack",
                    models.CharField(
                        help_text="Comma-separated tech tags", max_length=300
                    ),
                ),
                ("github_url", models.URLField(blank=True, null=True)),
                ("live_url", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
